type: deployment
name: de.tum.test.deployment.ingress_res
ttl:  0
actor_type:  de.tum.test.actor.ingress_res
actor_runtime_type:  lua
actor_version:  "0.1"
actor_code_file:  "http_ingress_resources.lua"